language: c
script: ./autogen.sh && ./configure && make V=0 && make distcheck

# Compile using both gcc & clang
compiler:
    - gcc
    - clang

# Use container based infrastructure
sudo: false
dist: trusty
addons:
    apt:
        packages:
        - libusb-1.0-0-dev
        - libudev-dev
